// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOt95AAmxlTOH4-mwRLEWfGkC7EopUWo',
    appId: '1:153052148740:web:310332f09eb3c4e0f83151',
    messagingSenderId: '153052148740',
    projectId: 'vcount1-b95c0',
    authDomain: 'vcount1-b95c0.firebaseapp.com',
    storageBucket: 'vcount1-b95c0.firebasestorage.app',
    measurementId: 'G-B2LPLG613S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxotGOdwrNni121txU7pOblg0qAawADfQ',
    appId: '1:153052148740:android:5ed799bc0e88fc04f83151',
    messagingSenderId: '153052148740',
    projectId: 'vcount1-b95c0',
    storageBucket: 'vcount1-b95c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4pwhIBctSHvdLmOmXlPCuQpeNCgC06g',
    appId: '1:153052148740:ios:61a047c73f0395ebf83151',
    messagingSenderId: '153052148740',
    projectId: 'vcount1-b95c0',
    storageBucket: 'vcount1-b95c0.firebasestorage.app',
    iosBundleId: 'com.example.vcount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4pwhIBctSHvdLmOmXlPCuQpeNCgC06g',
    appId: '1:153052148740:ios:61a047c73f0395ebf83151',
    messagingSenderId: '153052148740',
    projectId: 'vcount1-b95c0',
    storageBucket: 'vcount1-b95c0.firebasestorage.app',
    iosBundleId: 'com.example.vcount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOt95AAmxlTOH4-mwRLEWfGkC7EopUWo',
    appId: '1:153052148740:web:8fecbccbc43101a3f83151',
    messagingSenderId: '153052148740',
    projectId: 'vcount1-b95c0',
    authDomain: 'vcount1-b95c0.firebaseapp.com',
    storageBucket: 'vcount1-b95c0.firebasestorage.app',
    measurementId: 'G-GM3PQWQE6J',
  );
}
